"""add_kb_and_document_v2

Revision ID: e11545295b99
Revises: 9e40b96f2c42
Create Date: 2026-03-08 22:35:46.851259

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11545295b99'
down_revision: Union[str, Sequence[str], None] = '9e40b96f2c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('document', 'object_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.add_column('knowledge_base', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('knowledge_base_user_id_fkey'), 'knowledge_base', type_='foreignkey')
    op.drop_column('knowledge_base', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('knowledge_base_user_id_fkey'), 'knowledge_base', 'user', ['user_id'], ['id'])
    op.drop_column('knowledge_base', 'username')
    op.alter_column('document', 'object_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_column('document', 'username')
    # ### end Alembic commands ###
